//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AirportEntities : DbContext
    {
        public AirportEntities()
            : base("name=AirportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aircraft> Aircraft { get; set; }
        public virtual DbSet<AircraftRoute> AircraftRoute { get; set; }
        public virtual DbSet<BoardingPass> BoardingPass { get; set; }
        public virtual DbSet<Check_in> Check_in { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Luggage> Luggage { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual ObjectResult<PassengersOnFlight_Result> PassengersOnFlight(string flightID)
        {
            var flightIDParameter = flightID != null ?
                new ObjectParameter("FlightID", flightID) :
                new ObjectParameter("FlightID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PassengersOnFlight_Result>("PassengersOnFlight", flightIDParameter);
        }
    }
}
