//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlService
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardingPass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoardingPass()
        {
            this.Luggage = new HashSet<Luggage>();
        }
    
        public string BoardingPassID { get; set; }
        public string FlightID { get; set; }
        public string PassengerID { get; set; }
        public string CheckInManagerID { get; set; }
        public Nullable<System.DateTime> FlightTime { get; set; }
    
        public virtual Check_in Check_in { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Luggage> Luggage { get; set; }
    }
}
